# Generated by Django 3.0.4 on 2020-03-12 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled Event', max_length=255)),
                ('category', models.CharField(choices=[('Hangout', 'Hangout'), ('Band Event', 'Band Event'), ('Jam Sesh', 'Jam Sesh')], default='Hangout', max_length=255)),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('description', models.TextField()),
                ('location', models.CharField(default='Untitled Location', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendees', models.ManyToManyField(related_name='event', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
