# Generated by Django 3.0.4 on 2020-03-12 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200312_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='uri',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
