# Generated by Django 3.0.4 on 2020-03-12 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_uri'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='link',
            field=models.TextField(blank=True),
        ),
    ]
