# Generated by Django 3.0.4 on 2020-03-13 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200312_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='link',
        ),
    ]
