# Generated by Django 3.0.4 on 2020-03-13 15:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_userprofile_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='connections',
            field=models.ManyToManyField(blank=True, related_name='connections', to=settings.AUTH_USER_MODEL),
        ),
    ]
