# Generated by Django 3.0.4 on 2020-03-13 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200313_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='connections',
            field=models.ManyToManyField(blank=True, related_name='connections', to='accounts.Connection'),
        ),
    ]
