# Generated by Django 3.0.4 on 2020-03-13 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_userprofile_connections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connection',
            name='created',
        ),
    ]
