# Generated by Django 3.0.4 on 2020-03-16 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_connection_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connection',
            old_name='creator',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='connection',
            name='following',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
