# Generated by Django 3.0.4 on 2020-03-30 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20200316_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='BandProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('about', models.TextField()),
                ('uri', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('members', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
