# Generated by Django 3.0.4 on 2020-03-30 13:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_bandprofile_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bandprofile',
            name='members',
        ),
        migrations.AddField(
            model_name='bandprofile',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='members', to=settings.AUTH_USER_MODEL),
        ),
    ]
